### ISSUE TITLE
Crash when modifying Clocked Stretch 'clock' sub-chain.

### ISSUE THREAD

**Issue by stolmine** [odevices/er-301#39] opened 2021-06-28 08:06 UTC
Reproduced in 0.6.13.

1. Insert a Clocked Stretch unit and set its stretch duration config option to 'all.'
2. Return to the top level, enter the clock sub-chain. Attempting to assign the sub-chain's input freezes the machine.
3. Contrarily, inserting units in the sub-chain to generate gates does not induce a crash. Tested with Tap Tempo and Sine Osc units.
4. Similar results occurred with or without a buffer assigned.

**Comment by odevices** [comment] 2021-06-30 01:42
Turns out this has the same root cause as Issue #38 which is fixed in https://github.com/odevices/er-301/commit/0023678551ca566a0434e60206cba420f18b33d9.

**Closed by odevices** 2021-06-30 01:42 UTC
